name: publish_lua54

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build
          ./make_android_lua54.sh
          sudo apt install gcc-multilib
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_linux_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_ios_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
  osx:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_osx_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
  windows:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd build
          .\make_win_lua54.bat
          .\make_uwp_lua54.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54

  windows-luabin:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd build\luac
          .\make_win_lua54.bat
      - name: UploadLuabin54
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/bin_lua54/**/*
          name: bin_lua54

  publish:
    runs-on: ubuntu-latest
    needs: [windows,osx,ios,android,linux,windows-luabin]
    steps:         
      - uses: actions/download-artifact@v1
        with:
          name: plugin_lua54
          path: plugin_lua54/
          
      - uses: actions/download-artifact@v1
        with:
          name: bin_lua54
          path: bin_lua54/
          
      - name: Create Release Asset
        run: |
          cd plugin_lua54/ && tar cvfz ../lua54_${{ github.event.inputs.tag_name }}.tgz Plugins && cd -
          tar cvfz bin_lua54_${{ github.event.inputs.tag_name }}.tgz bin_lua54
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Tag:${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
          
      - name: Upload lua54 Plugins
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lua54_${{ github.event.inputs.tag_name }}.tgz
          asset_name: lua54_${{ github.event.inputs.tag_name }}.tgz
          asset_content_type: application/tgz
          
      - name: Upload lua54 bin_lua54
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin_lua54_${{ github.event.inputs.tag_name }}.tgz
          asset_name: bin_lua54_${{ github.event.inputs.tag_name }}.tgz
          asset_content_type: application/tgz
   
